# Generated by Django 5.1.3 on 2024-11-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('images', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.JSONField()),
                ('available_today', models.BooleanField(default=False)),
            ],
        ),
    ]
