# Generated by Django 5.1.3 on 2024-11-12 08:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('type', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=50)),
                ('desc', models.TextField()),
                ('images', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.JSONField()),
                ('available_today', models.BooleanField(default=True)),
                ('shared_shower', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('guest_email', models.EmailField(default=None, max_length=50)),
                ('guest_first_name', models.CharField(default=None, max_length=100)),
                ('guest_last_name', models.CharField(default=None, max_length=100)),
                ('adult_number', models.IntegerField(default=0)),
                ('children_number', models.IntegerField(default=0)),
                ('special_request', models.CharField(blank=True, max_length=200, null=True)),
                ('guest_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "0912345678". Up to 15 digits allowed.', regex='^\\+?\\d{10,15}$')])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.rooms')),
            ],
        ),
    ]
