# Generated by Django 5.1.3 on 2024-11-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_reservation_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tx_ref',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
