# Generated by Django 5.1.3 on 2024-11-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_rooms_options_alter_rooms_room_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], default='single', max_length=50),
        ),
    ]
