# Generated by Django 5.1.3 on 2024-11-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_reservation_tx_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='adult_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='children_number',
        ),
    ]
