# Generated by Django 5.1.3 on 2024-11-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_reservation_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='guest_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phone_number',
            new_name='guest_phone',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='available_today',
            field=models.BooleanField(default=True),
        ),
    ]
