# Generated by Django 5.1.3 on 2024-11-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_reservation_adult_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('without_conflict', models.BooleanField(default=True)),
                ('event', models.CharField(choices=[('payout.success', 'Payout Success')], max_length=20)),
                ('type', models.CharField(choices=[('Payout', 'Payout')], max_length=10)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=15)),
                ('bank_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('ETB', 'ETB')], max_length=3)),
                ('status', models.CharField(choices=[('success', 'Success')], max_length=10)),
                ('reference', models.CharField(max_length=20)),
                ('chapa_reference', models.CharField(max_length=20)),
                ('bank_reference', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Transaction log',
                'verbose_name_plural': 'Transaction logs',
            },
        ),
    ]
