# Generated by Django 5.1.3 on 2024-11-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rename_name_reservation_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='shared_shower',
            field=models.BooleanField(default=False),
        ),
    ]
