# Generated by Django 5.1.3 on 2024-11-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_transactionlogs_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlogs',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='account_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
