# Generated by Django 5.1.3 on 2024-11-11 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rooms_shared_shower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "0912345678". Up to 15 digits allowed.', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
