# Generated by Django 5.1.3 on 2024-11-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_transactionlogs_chapa_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlogs',
            old_name='bank_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='transactionlogs',
            old_name='account_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='transactionlogs',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='transactionlogs',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='transactionlogs',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='transactionlogs',
            name='chapa_reference',
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='customization',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='mode',
            field=models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='live', max_length=10),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionlogs',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='event',
            field=models.CharField(choices=[('charge.success', 'Charge Success')], default='charge.success', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='type',
            field=models.CharField(choices=[('API', 'API'), ('Manual', 'Manual')], default='API', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionlogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
