# Generated by Django 5.1.3 on 2024-11-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_rename_bank_name_transactionlogs_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='available_today',
            new_name='is_ready',
        ),
    ]
